export const EVENT_FETCH_START = 'EVENT_FETCH_START'
export const EVENT_FETCH_FINISH = 'EVENT_FETCH_FINISH'
export const EVENT_FETCH_POPULAR_START = 'EVENT_FETCH_POPULAR_START'
export const EVENT_FETCH_POPULAR_FINISH = 'EVENT_FETCH_POPULAR_FINISH'
